### ISSUE TITLE
靠大模型生成点和边感觉不稳定,有什么其他方式吗

### ISSUE THREAD

**Issue by wangsen3** [xuzeyu91/GraphRag.Net#8]

**Comment by xuzeyu91** [comment]
GraphRag主要是靠大模型来生成的，当然也可以使用传统的人工梳理的方式，做好了知识图谱来做RAG

**Comment by RockNHawk** [comment]
换用 其它模型都提示 Json mode is not supported for this model.
是不是只有 gpt 模型支持 json 格式输出呀。
